[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
slvt_core = "5rzosayUo9e8CmXit4ydqu8uk3tCGFFqUdhHCASFe5ho"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/susd-core.ts"

[hooks]
