[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
susd_core = "2jHyq6V2wcxHSA1Wk4shY3B4bZooKoW1VjMWnagd1tda"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm run test"

[hooks]
